# action.yml
name: 'Pelican to Github Pages'
description: 'Generate the Pelican output and deploy to Github Pages'

branding:
  icon: 'home'
  color: 'red'

runs:
  using: 'docker'
  image: 'Dockerfile'  

inputs:
  PELICAN_CONFIG_FILE:
    description: 'override the default `publishconf.py` config file'
    required: false
    default: publishconf.py
  PELICAN_CONTENT_FOLDER:
    description: 'override the default `content` content folder'
    required: false
    default: content
  PELICAN_OUTPUT_FOLDER:
    description: 'override the default `output` output folder'
    required: false
    default: output